name: mlops-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - git
  - curl

  - numpy=1.26.4
  - pandas=2.2.3
  - matplotlib=3.9.2
  - scikit-learn=1.7.0

  - jupyter
  - jupyterlab

  - pip:
      - -r requirements.txt